# Generated by Django 2.0.4 on 2018-04-21 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cowapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cow',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='cowapp.Cow'),
        ),
    ]
