# Generated by Django 2.0.4 on 2018-06-22 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cowapp', '0002_auto_20180622_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cow',
            name='number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='cow',
            unique_together={('user', 'number')},
        ),
    ]
