# Generated by Django 2.0.4 on 2018-06-22 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cowapp', '0003_record'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cow',
            options={'ordering': ('birthday', 'created')},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ('day', 'created')},
        ),
        migrations.AlterField(
            model_name='cow',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cow',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='cowapp.Cow'),
        ),
        migrations.AlterField(
            model_name='record',
            name='day',
            field=models.DateField(),
        ),
    ]
