# Generated by Django 2.0.4 on 2018-06-25 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cowapp', '0004_cow_mother_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cow',
            name='mother',
        ),
    ]
