# Generated by Django 2.0.4 on 2018-06-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowapp', '0004_auto_20180622_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cow',
            name='number',
            field=models.TextField(unique=True),
        ),
    ]
